[package]
name = "regez"
version = "0.0.1"
authors = ["actuallylost"]
readme = "README.md"
repository = "https://github.com/actuallylost/regez"
edition = "2021"
publish = true

[workspace]
members = [
    "crates/*",
]

[[test]]
path = "tests/lib.rs"

[profile.release]
debug = true

[profile.dev]
opt-level = 3
debug = true

[profile.test]
opt-level = 3
debug = true